# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+9999999999'. Up to 10 digits allowed", regex=b'^\\+?1?\\d{9,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
                ('salary', models.FloatField()),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
